import org.macmap.Event
import org.macmap.Person
import org.macmap.Place
import org.macmap.User

class BootStrap {

    def init = { servletContext ->
        Place or241 = new Place(name: "Classroom", number:241).save(failOnError: true)
        Place or243 = new Place(name: "Classroom", number:243).save(failOnError: true)
        Place or245 = new Place(name: "Classroom", number:245).save(failOnError: true)
        Place or247 = new Place(name: "Classroom", number:247).save(failOnError: true)
        Place or249 = new Place(name: "Study Room", number:249).save(failOnError: true)
        Place or248 = new Place(name: "Study Room", number:248).save(failOnError: true)
        Place or257 = new Place(name: "Math/Comp Sci. Comp Lab", number:257).save(failOnError: true)
        Place or259 = new Place(name: "Math/Comp Sci. Comp. Lab", number:259).save(failOnError: true)
        Place or246 = new Place(name: "Math/Comp Sci. Storage", number:246).save(failOnError: true)
        Place or255 = new Place(name: "Math/Comp Sci. Storage", number:255).save(failOnError: true)
        Place or258 = new Place(name: "Math/Comp Sci. Lab", number:258).save(failOnError: true)
        Place or256 = new Place(name: "Math/Comp Sci. Lab", number:256).save(failOnError: true)
        Place or254 = new Place(name: "Math/Comp sci ref. room", number:254).save(failOnError: true)
        Place or252 = new Place(name: "Copy/Mail Room", number:252).save(failOnError: true)
        Place or252A = new Place(name: "Storage", number:252, roomDes:'A').save(failOnError: true)
        Place or208 = new Place(name: "Women's", number:208).save(failOnError: true)
        Place or205 = new Place(name: "Symposium", number:205).save(failOnError: true)
        Place or205D = new Place(name: "No name", number:205, roomDes:'D').save(failOnError: true)
        Place or205E = new Place(name: "Sto", number:205, roomDes:'E').save(failOnError: true)
        Place or253 = new Place(name: "Prep room", number:253).save(failOnError: true)
        Place or250 = new Place(name: "Lecture", number:250).save(failOnError: true)
        Place or240 = new Place(name: "Cust", number:240).save(failOnError: true)
        Place or240A = new Place(name: "Tel. Clo", number:240, roomDes:'A').save(failOnError: true)
        Place or240B = new Place(name: "Elec. Clo", number:240, roomDes:'B').save(failOnError: true)
        Place or205A = new Place(name: "Pantry", number:205, roomDes:'A').save(failOnError: true)
        Place or200 = new Place(name: "Lobby", number:200).save(failOnError: true)
        Place or206 = new Place(name: "Lobby", number:206).save(failOnError: true)
        Place or222 = new Place(name: "Dept. Office", number:222).save(failOnError: true)
        Place or223 = new Place(name: "Faculty Office", number:223).save(failOnError: true)
        Place or224 = new Place(name: "Faculty Office", number:224).save(failOnError: true)
        Place or225 = new Place(name: "Faculty Office", number:225).save(failOnError: true)
        Place or226 = new Place(name: "Faculty Office", number:226).save(failOnError: true)
        Place or227 = new Place(name: "Faculty Office", number:227).save(failOnError: true)
        Place or228 = new Place(name: "Faculty Office", number:228).save(failOnError: true)
        Place or229 = new Place(name: "Faculty Office", number:229).save(failOnError: true)
        Place or230 = new Place(name: "Faculty Office", number:230).save(failOnError: true)
        Place or231 = new Place(name: "Faculty Office", number:231).save(failOnError: true)
        Place or232 = new Place(name: "Faculty Office", number:232).save(failOnError: true)
        Place or233 = new Place(name: "Faculty Office", number:233).save(failOnError: true)
        Place or201 = new Place(name: "DN", number:201).save(failOnError: true)
        Place or297 = new Place(name: "UP DN", number:297).save(failOnError: true)
        Place or207 = new Place(name: "DN UP", number:207).save(failOnError: true)
        Place or284 =new Place (name:"Biology Teaching Lab",number: 284).save(failOnError: true)
        Place or285 =new Place (name:"Biology Teaching Lab",number: 285).save(failOnError: true)
        Place or286 =new Place (name:"Biology Prep Room",number: 286).save(failOnError: true)
        Place or287 =new Place (name:"Biology Teaching Lab",number: 287).save(failOnError: true)
        Place or283 =new Place (name:"Biology Research Lab",number: 283).save(failOnError: true)
        Place or282 =new Place (name:"Storage",number: 252).save(failOnError: true)
        Place or281 =new Place (name:"Biology Research Lab",number: 281).save(failOnError: true).save(failOnError: true)
        Place or278 =new Place (name:"Biology Computer Lab",number: 278).save(failOnError: true)
        Place or280 =new Place (name:"Biology Research Lab",number: 280).save(failOnError: true)
        Place or276 =new Place (name:"Biology Research Lab",number: 276).save(failOnError: true)
        Place or274B =new Place (name:"Cust",number: 274,roomDes: 'B').save(failOnError: true)
        Place or274a =new Place (name:"Elec Clo",number: 284, roomDes: 'A').save(failOnError: true)
        Place or274 =new Place (name:"Tel Clo",number: 274).save(failOnError: true)
        Place or272 =new Place (name:"Biology Reference Lab",number: 272).save(failOnError: true)
        Place or270 =new Place (name:"Seminar",number: 270).save(failOnError: true)
        Place or288A =new Place (name:"Class Wash",number: 288, roomDes: 'A').save(failOnError: true)
        Place or288 =new Place (name:"No Name",number: 288).save(failOnError: true)
        Place or288B =new Place (name:"Prep Lab",number: 288, roomDes: 'B').save(failOnError: true)
        Place or289 =new Place (name:"Biology Teaching Lab",number: 289).save(failOnError: true)
        Place or290 =new Place (name:"Biology Cold Room",number: 290).save(failOnError: true)
        Place or260 =new Place (name:"Biology Research Lab",number: 260).save(failOnError: true)
        Place or299 =new Place (name:"Stair",number: 299).save(failOnError: true)
        Place or261 =new Place (name:"Elevator",number: 261).save(failOnError: true)
        Place or210 =new Place (name:"Faculty Office",number: 210).save(failOnError: true)
        Place or211 =new Place (name:"Faculty Office",number: 211).save(failOnError: true)
        Place or212 =new Place (name:"Faculty Office",number: 212).save(failOnError: true)
        Place or213 =new Place (name:"Faculty Office",number: 213).save(failOnError: true)
        Place or214 =new Place (name:"Faculty Office",number: 214).save(failOnError: true)
        Place or215 =new Place (name:"Faculty Office",number: 215).save(failOnError: true)
        Place or216 =new Place (name:"Faculty Office",number: 216).save(failOnError: true)
        Place or217 =new Place (name:"Faculty Office",number: 217).save(failOnError: true)
        Place or218 =new Place (name:"Faculty Office",number: 218).save(failOnError: true)
        Place or219 =new Place (name:"Faculty Office",number: 219).save(failOnError: true)
        Place or220 =new Place (name:"Faculty Office",number: 220).save(failOnError: true)
        Place or221 =new Place (name:"Dept Office",number: 221).save(failOnError: true)
        Place or277 =new Place (name:"Biology Teaching Lab",number: 277).save(failOnError: true)
        Place or275 =new Place (name:"Biology Teaching Lab",number: 275).save(failOnError: true)
        Place or275A =new Place (name:"Vest.",number: 275, roomDes: 'A').save(failOnError: true)
        Place or275B =new Place (name:"Sto.",number: 275, roomDes: 'B').save(failOnError: true)
        Place or262 =new Place (name:"Biology Research Lab",number: 262).save(failOnError: true)
        Place or263 =new Place (name:"Biology Research Lab",number: 263).save(failOnError: true)
        Place or264 =new Place (name:"Biology Research Lab",number: 264).save(failOnError: true)
        Place or209 =new Place (name:"Men's",number: 262).save(failOnError: true)
        Place or273 =new Place (name:"Biology Teaching Lab",number: 273).save(failOnError: true)
        Place or271A =new Place (name:"Biology Prep",number: 271, roomDes: 'A').save(failOnError: true)
        Place or271 =new Place (name:"Biology Storage",number: 271).save(failOnError: true)
        Place or298 =new Place (name:"Stairs",number: 298).save(failOnError: true)

        Date d1=new Date()
        Date d2=new Date()
        Event e=new Event(eventName: "Macathon", place: or256, start: d1, end: d2)
        e.addToPeople(new Person(name: "Grand Dictator"))
        e.addToPeople(new Person(name: "Master of .pptx"))
        e.addToPeople(new Person(name: "Cartographer"))
        e.addToPeople(new Person(name: "Slave Rat #1"))
        e.addToPeople(new Person(name: "Slave Rat #2"))
        e.save(failOnError: false)


        Person aaronP = new Person(name: "Aaron").save()
        User aaron=new User(userName: "aaron", whoID: aaronP.id, calURL: "https://www.google.com/calendar/ical/lvdtrmnnubk55ebu7npuin1ojc%40group.calendar.google.com/private-0d5e8933c8e4901ab3a33f12d359722e/basic.ics", userID: 1, userPass: "laursen").save()



    }
    def destroy = {
    }
}
