import org.macmap.Event
import org.macmap.Person
import org.macmap.Place

class BootStrap {

    def init = { servletContext ->
        Place or241 = new Place(name: "Classroom", number:241)
        Place or243 = new Place(name: "Classroom", number:243)
        Place or245 = new Place(name: "Classroom", number:245)
        Place or247 = new Place(name: "Classroom", number:247)
        Place or249 = new Place(name: "Study Room", number:249)
        Place or248 = new Place(name: "Study Room", number:248)
        Place or257 = new Place(name: "Math/Comp Sci. Comp Lab", number:257)
        Place or259 = new Place(name: "Math/Comp Sci. Comp. Lab", number:259)
        Place or246 = new Place(name: "Math/Comp Sci. Storage", number:246)
        Place or255 = new Place(name: "Math/Comp Sci. Storage", number:255)
        Place or258 = new Place(name: "Math/Comp Sci. Lab", number:258)
        Place or256 = new Place(name: "Math/Comp Sci. Lab", number:256)
        Place or254 = new Place(name: "Math/Comp sci ref. room", number:254)
        Place or252 = new Place(name: "Copy/Mail Room", number:252)
        Place or252A = new Place(name: "Storage", number:252, roomDes:'A')
        Place or208 = new Place(name: "Women's", number:208)
        Place or205 = new Place(name: "Symposium", number:205)
        Place or205D = new Place(name: "No name", number:205, roomDes:'D')
        Place or205E = new Place(name: "Sto", number:205, roomDes:'E')
        Place or253 = new Place(name: "Prep room", number:253)
        Place or250 = new Place(name: "Lecture", number:250)
        Place or240 = new Place(name: "Cust", number:240)
        Place or240A = new Place(name: "Tel. Clo", number:240, roomDes:'A')
        Place or240B = new Place(name: "Elec. Clo", number:240, roomDes:'B')
        Place or205A = new Place(name: "Pantry", number:205, roomDes:'A')
        Place or200 = new Place(name: "Lobby", number:200)
        Place or206 = new Place(name: "Lobby", number:206)
        Place or222 = new Place(name: "Dept. Office", number:222)
        Place or223 = new Place(name: "Faculty Office", number:223)
        Place or224 = new Place(name: "Faculty Office", number:224)
        Place or225 = new Place(name: "Faculty Office", number:225)
        Place or226 = new Place(name: "Faculty Office", number:226)
        Place or227 = new Place(name: "Faculty Office", number:227)
        Place or228 = new Place(name: "Faculty Office", number:228)
        Place or229 = new Place(name: "Faculty Office", number:229)
        Place or230 = new Place(name: "Faculty Office", number:230)
        Place or231 = new Place(name: "Faculty Office", number:231)
        Place or232 = new Place(name: "Faculty Office", number:232)
        Place or233 = new Place(name: "Faculty Office", number:233)
        Place or201 = new Place(name: "DN", number:201)
        Place or297 = new Place(name: "UP DN", number:297)
        Place or207 = new Place(name: "DN UP", number:207)
        Place or284 =new Place (name:"Biology Teaching Lab",number: 284)
        Place or285 =new Place (name:"Biology Teaching Lab",number: 285)
        Place or286 =new Place (name:"Biology Prep Room",number: 286)
        Place or287 =new Place (name:"Biology Teaching Lab",number: 287)
        Place or283 =new Place (name:"Biology Research Lab",number: 283)
        Place or282 =new Place (name:"Storage",number: 252)
        Place or281 =new Place (name:"Biology Research Lab",number: 281)
        Place or278 =new Place (name:"Biology Computer Lab",number: 278)
        Place or280 =new Place (name:"Biology Research Lab",number: 280)
        Place or276 =new Place (name:"Biology Research Lab",number: 276)
        Place or274B =new Place (name:"Cust",number: 274,roomDes: 'B')
        Place or274a =new Place (name:"Elec Clo",number: 284, roomDes: 'A')
        Place or274 =new Place (name:"Tel Clo",number: 274)
        Place or272 =new Place (name:"Biology Reference Lab",number: 272)
        Place or270 =new Place (name:"Seminar",number: 270)
        Place or288A =new Place (name:"Class Wash",number: 288, roomDes: 'A')
        Place or288 =new Place (name:"No Name",number: 288)
        Place or288B =new Place (name:"Prep Lab",number: 288, roomDes: 'B')
        Place or289 =new Place (name:"Biology Teaching Lab",number: 289)
        Place or290 =new Place (name:"Biology Cold Room",number: 290)
        Place or260 =new Place (name:"Biology Research Lab",number: 260)
        Place or299 =new Place (name:"Stair",number: 299)
        Place or261 =new Place (name:"Elevator",number: 261)
        Place or210 =new Place (name:"Faculty Office",number: 210)
        Place or211 =new Place (name:"Faculty Office",number: 211)
        Place or212 =new Place (name:"Faculty Office",number: 212)
        Place or213 =new Place (name:"Faculty Office",number: 213)
        Place or214 =new Place (name:"Faculty Office",number: 214)
        Place or215 =new Place (name:"Faculty Office",number: 215)
        Place or216 =new Place (name:"Faculty Office",number: 216)
        Place or217 =new Place (name:"Faculty Office",number: 217)
        Place or218 =new Place (name:"Faculty Office",number: 218)
        Place or219 =new Place (name:"Faculty Office",number: 219)
        Place or220 =new Place (name:"Faculty Office",number: 220)
        Place or221 =new Place (name:"Dept Office",number: 221)
        Place or277 =new Place (name:"Biology Teaching Lab",number: 277)
        Place or275 =new Place (name:"Biology Teaching Lab",number: 275)
        Place or275A =new Place (name:"Vest.",number: 275, roomDes: 'A')
        Place or275B =new Place (name:"Sto.",number: 275, roomDes: 'B')
        Place or262 =new Place (name:"Biology Research Lab",number: 262)
        Place or263 =new Place (name:"Biology Research Lab",number: 263)
        Place or264 =new Place (name:"Biology Research Lab",number: 264)
        Place or209 =new Place (name:"Men's",number: 262)
        Place or273 =new Place (name:"Biology Teaching Lab",number: 273)
        Place or271A =new Place (name:"Biology Prep",number: 271, roomDes: 'A')
        Place or271 =new Place (name:"Biology Storage",number: 271)
        Place or298 =new Place (name:"Stairs",number: 298)





    }
    def destroy = {
    }
}
